### ISSUE TITLE
Making grass with a knife interaction

### ISSUE THREAD

**Issue by Aspyro** [CannoliCatfish/project-rankine#145]
Using a knife on a Grass block creates grass _in_ the grass block. Because of that, the grass is ejected out way too far (4 or 5 blocks away it seems, as it escaped from suffocation).
Wouldn't it be better to make it appear _above_ the grass block ?

(Forge and Project Rankine always to last update before playing)

**Comment by CannoliCatfish** [comment]
Thank you for your suggestion. This will be fixed in the Version 1.2 update.
