### ISSUE TITLE
Pinyon pine planks don't drop planks when broken

### ISSUE THREAD

**Issue by captaincoen** [CannoliCatfish/project-rankine#194]
I have discovered an issue with the pinyon pines in the most recent version of the mod. If you place a pinyon pine plank and cut it, it drops a log instead. I'm going to investigate other issues with the planks from this mod.

**Comment by captaincoen** [comment]
I have discovered an additional bug in the planks while testing this. Magnolia planks seem to drop nothing when broken. It doesn't matter how they are broken, whether by hand or tnt, they will drop nothing.

The pinyon pine planks still provide the same bug.

**Comment by CannoliCatfish** [comment]
Thank you for the report! These bugs are fixed in the most recent update.
