### ISSUE TITLE
Unknown client-side crash on modded server whenever opening up inventory with alloy template

### ISSUE THREAD

**Issue by Kzeroko** [CannoliCatfish/project-rankine#223]
[crash-2021-10-18_12.52.25-client.txt](https://github.com/CannoliCatfish/project-rankine/files/7364650/crash-2021-10-18_12.52.25-client.txt)
It happens to any sort of inventory, including backpack. I have tried removing every shade pack and texture pack but it did not work :(
Edit: nvm I just saw a closed issue with the same problem, waiting for the next update.

**Comment by CannoliCatfish** [comment]
This has been fixed as of Version 1.3.
