### ISSUE TITLE
Startup error upgrading from alpha 2 to 3

### ISSUE THREAD

**Issue by aburone** [CannoliCatfish/project-rankine#240]
To reproduce:
* Upgrade from alpha 2 to alpha 3
* try lo load minecraft

Failure message: Project Rankine (rankine) encountered an error during the common_setup event phase
java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 6

https://www.toptal.com/developers/hastebin/ifahulamol.rb

**Comment by CannoliCatfish** [comment]
This is likely an issue regarding the config, as throughout the alpha we have been changing the requirements for certain fields in our config. Please delete your current version of the config and attempt relaunch to see if the error still occurs.

**Comment by aburone** [comment]
Ok. Removing the config files now it started 
👍
