### ISSUE TITLE
[bug] Recipe returns null cause NPE

### ISSUE THREAD

**Issue by khjxiaogu** [CannoliCatfish/project-rankine#262]
*Some of the recipe returns null in method getRecipeOutput, which supposed to be ItemStack.EMPTY according to forge comments:
> Get the result of this recipe, usually for display purposes (e.g. recipe book). If your recipe has more than one
> possible result (e.g. it's dynamic and depends on its inputs), then return an empty stack.

This cause incompatibility to many other mods with auto recipe generator and crash game with NPE.

**Comment by CannoliCatfish** [comment]
Thank you, we caught this error as well. It will be fixed in a small update coming soon.

**Comment by CannoliCatfish** [comment]
This bug is fixed as of Version 1.3.1.
