### ISSUE TITLE
FOV reduced when walking on terrain that lowers speed and FOV effects setting is changed

### ISSUE THREAD

**Issue by yangbowen** [CannoliCatfish/project-rankine#270]
When the video setting "FOV effects" is reduced from 100% and the player steps on terrain that lowers player speed (e.g. dirt), the actual FOV is heavily reduced, as opposed to being closer to the "FOV" option. I suppose that the mod increases FOV to cancel out the FOV reducing effect in lower speed, but the FOV increasing is unexpectedly influenced by the setting "FOV effects"?

**Comment by CannoliCatfish** [comment]
This issue is now resolved with a new config option and changed functionality as of the most recent hotfix for Version 1.3.2.
