### ISSUE TITLE
Connection to multiplayer failed

### ISSUE THREAD

**Issue by OcrSu** [CannoliCatfish/project-rankine#272]
![9_E~V8_G$C_09MGOB7BMQ`W](https://user-images.githubusercontent.com/75876201/165913422-6d3c86e0-dba7-427c-bd99-d83638758077.png)

Java11

**Comment by OcrSu** [comment]
Using version 1.3.2 causes problems
The problem disappears when reverting to 1.3.1hotfix 1

**Comment by CannoliCatfish** [comment]
This issue is now fixed as of the most recent hotfix for Version 1.3.2.
