### ISSUE TITLE
Charcoal pit never finishes

### ISSUE THREAD

**Issue by craft90** [CannoliCatfish/project-rankine#277]
I've tried to work the charcoal pit several times now. But no matter what I do, nothing seems to happen. I put down the logs. Tried both a 3x3 with the charcoal pit both on the top and in the middle. I light it just fine. After awhile the charcoal pit goes invisible and when I look through it there's a bunch of ash around it. But when I then hit the block it reappears. Breaking the construction apart also reveals piles of ash. But when you try to harvest them, they revert to logs. I'm making another try with a 3 column of logs and the pit on top. But the same issue reappears. The block goes invisible and it looks done. But as soon as you hit it it reappears.

**Comment by Jemmerl** [comment]
Noticed this as well. They also are able to process uncovered, and revert when interacted with in the same manner

**Comment by CannoliCatfish** [comment]
This issue is now fixed as of the most recent hotfix for Version 1.3.2.
