### ISSUE TITLE
[1.16]Crafting recipe for stairs to block cause dupe

### ISSUE THREAD

**Issue by khjxiaogu** [CannoliCatfish/project-rankine#326]
![PNS{IFWXZ8Z%JS1803RVTOV](https://user-images.githubusercontent.com/54445543/195385904-c1d00054-6d16-425d-83ae-eb23627b79cd.png)
![76 V`)E73`4R_J6TP {V}T0](https://user-images.githubusercontent.com/54445543/195385966-314882ce-8707-4f1d-a13d-a9429750fe84.png)
4->6

**Comment by CannoliCatfish** [comment]
Fixed as of most recent hotfix.
