### ISSUE TITLE
Rankine 1.18.2-1.3.5. Fails to load on forge 40.1.86

### ISSUE THREAD

**Issue by CrackedEmerald** [CannoliCatfish/project-rankine#334]
[crash-2022-12-10_14.11.22-fml.txt](https://github.com/CannoliCatfish/project-rankine/files/10200567/crash-2022-12-10_14.11.22-fml.txt)

**Comment by CannoliCatfish** [comment]
This appears to be an issue with your config. Try deleting your config to refresh and see if that fixes the problem. If you are still crashing, please let us know.

**Comment by CrackedEmerald** [comment]
thanks, i deleted the ones with "rankine" in the name and it worked.

**Comment by CannoliCatfish** [comment]
Closed as issue is resolved.
