### ISSUE TITLE
Cant craft "Mg ingot" with MgCl 

### ISSUE THREAD

**Issue by Threxion** [CannoliCatfish/project-rankine#354]
![Mg ingot](https://user-images.githubusercontent.com/66978725/229156279-ff27d71b-8497-4d98-9608-5c6912956b89.png)
![Mg2](https://user-images.githubusercontent.com/66978725/229156377-1c559cb0-a702-4a1d-8a20-2a51129f6131.png)

cuz same recipe?

**Comment by CannoliCatfish** [comment]
This issue should be fixed as of the most recent versions for 1.16.5 and 1.18.2 of Project Rankine. Which version of Project Rankine are you using?

**Comment by Threxion** [comment]
my mod version is 1.3.2 hf5, game version is 1.16.5, play with a modpack;
 I'm glad to hear that bug has been fixed ^ ^
