### ISSUE TITLE
[1.16.1] Alloy Furnace Problem

### ISSUE THREAD

**Issue by Rumaruka** [CannoliCatfish/project-rankine#89]
Maybe I'm stupid, but don`t work alloy furnace

![image](https://user-images.githubusercontent.com/8148679/90113612-0dbdc080-dd6b-11ea-9969-d5d138a1c47e.png)
With redstone signal
![image](https://user-images.githubusercontent.com/8148679/90113665-229a5400-dd6b-11ea-8cfe-52c7257d4a33.png)

**Comment by CannoliCatfish** [comment]
Thank you for your report! From what I can tell, the copper you are using may be coming from another mod. Currently, other mod's ingots may not work or be recognized in the alloy furnace. We plan to use the tag system in a coming update to make the alloy furnace more compatible with other mods.

**Comment by Rumaruka** [comment]
Oh, I'm checked about this =)

**Comment by Rumaruka** [comment]
Nope, both ingot in your mod =(
![image](https://user-images.githubusercontent.com/8148679/90172991-31115b80-ddbd-11ea-9a38-472d7ad2df24.png)

**Comment by Rumaruka** [comment]
Oh i found solution D:
Sorry about my idiotism =(
Closed
