### ISSUE TITLE
Beehive Oven Pit

### ISSUE THREAD

**Issue by davqvist** [CannoliCatfish/project-rankine#98]
Forge 32.0.108
Rankine 1.0.7

So I love the mod so far, but for the life of me I can't figure out how the Beehive Oven Pit works. I read the JEI tooltip and the advancement, but it doesn't work, I tried 3x1x3 and 3x3x3, blocks on top, blocks also on the side, all did not work, the fire on top of the pit constantly goes out without anything happening. Is it bugged or how is the correct setup? Would love some info!

**Comment by CannoliCatfish** [comment]
Great to hear you are enjoying the mod!

Any Beehive Oven Pit should be placed in the center of 8 refractory bricks (of its type) and then can be lit with a flint and steel. Then, any blocks you want to cook with the pit should be placed above the 8 refractory bricks while leaving the center open and visible to the sky. The pit does take a long time to cook blocks, but its frequency increases with the type of Beehive Oven pit used. The pit will also turn off automatically if it detects that there are no more blocks it can burn or if the requirements for placement are no longer met. 

The description in JEI does seem ambiguous, so it will be improved for clarity in the next update.

![image](https://user-images.githubusercontent.com/6697209/91742052-9e760800-eb83-11ea-8d58-5aad6c3e359c.png)

**Comment by davqvist** [comment]
Thanks a lot, I will try it out. Thanks for the quick answer.
Btw, do you have a discord or plan to make one? I have several small questions that aren't really worth an issue on github.

**Comment by CannoliCatfish** [comment]
Yes, we now have a discord at: https://discord.gg/EBtSqDN.
